/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShippingRouteImport } from './routes/_authenticated/shipping'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdSpendRouteImport } from './routes/_authenticated/ad-spend'
import { Route as AuthenticatedAdAccountsRouteImport } from './routes/_authenticated/ad-accounts'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedMarketersIndexRouteImport } from './routes/_authenticated/marketers.index'
import { Route as AuthenticatedSettingsMappingsRouteImport } from './routes/_authenticated/settings.mappings'
import { Route as AuthenticatedProductsNameRouteImport } from './routes/_authenticated/products.$name'
import { Route as AuthenticatedOrdersUpdateStatusRouteImport } from './routes/_authenticated/orders.update-status'
import { Route as AuthenticatedOrdersImportRouteImport } from './routes/_authenticated/orders.import'
import { Route as AuthenticatedMarketersIdRouteImport } from './routes/_authenticated/marketers.$id'
import { Route as AuthenticatedAdAccountsConnectMetaRouteImport } from './routes/_authenticated/ad-accounts_.connect-meta'
import { Route as AuthenticatedMarketersIdExpensesRouteImport } from './routes/_authenticated/marketers.$id.expenses'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShippingRoute = AuthenticatedShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdSpendRoute = AuthenticatedAdSpendRouteImport.update({
  id: '/ad-spend',
  path: '/ad-spend',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdAccountsRoute = AuthenticatedAdAccountsRouteImport.update({
  id: '/ad-accounts',
  path: '/ad-accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedMarketersIndexRoute =
  AuthenticatedMarketersIndexRouteImport.update({
    id: '/marketers/',
    path: '/marketers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMappingsRoute =
  AuthenticatedSettingsMappingsRouteImport.update({
    id: '/settings/mappings',
    path: '/settings/mappings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNameRoute =
  AuthenticatedProductsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedOrdersUpdateStatusRoute =
  AuthenticatedOrdersUpdateStatusRouteImport.update({
    id: '/update-status',
    path: '/update-status',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedOrdersImportRoute =
  AuthenticatedOrdersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedMarketersIdRoute =
  AuthenticatedMarketersIdRouteImport.update({
    id: '/marketers/$id',
    path: '/marketers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdAccountsConnectMetaRoute =
  AuthenticatedAdAccountsConnectMetaRouteImport.update({
    id: '/ad-accounts_/connect-meta',
    path: '/ad-accounts/connect-meta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketersIdExpensesRoute =
  AuthenticatedMarketersIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMarketersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ad-accounts': typeof AuthenticatedAdAccountsRoute
  '/ad-spend': typeof AuthenticatedAdSpendRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/shipping': typeof AuthenticatedShippingRoute
  '/ad-accounts/connect-meta': typeof AuthenticatedAdAccountsConnectMetaRoute
  '/marketers/$id': typeof AuthenticatedMarketersIdRouteWithChildren
  '/orders/import': typeof AuthenticatedOrdersImportRoute
  '/orders/update-status': typeof AuthenticatedOrdersUpdateStatusRoute
  '/products/$name': typeof AuthenticatedProductsNameRoute
  '/settings/mappings': typeof AuthenticatedSettingsMappingsRoute
  '/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/marketers/$id/expenses': typeof AuthenticatedMarketersIdExpensesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ad-accounts': typeof AuthenticatedAdAccountsRoute
  '/ad-spend': typeof AuthenticatedAdSpendRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/shipping': typeof AuthenticatedShippingRoute
  '/ad-accounts/connect-meta': typeof AuthenticatedAdAccountsConnectMetaRoute
  '/marketers/$id': typeof AuthenticatedMarketersIdRouteWithChildren
  '/orders/import': typeof AuthenticatedOrdersImportRoute
  '/orders/update-status': typeof AuthenticatedOrdersUpdateStatusRoute
  '/products/$name': typeof AuthenticatedProductsNameRoute
  '/settings/mappings': typeof AuthenticatedSettingsMappingsRoute
  '/marketers': typeof AuthenticatedMarketersIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/marketers/$id/expenses': typeof AuthenticatedMarketersIdExpensesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ad-accounts': typeof AuthenticatedAdAccountsRoute
  '/_authenticated/ad-spend': typeof AuthenticatedAdSpendRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/shipping': typeof AuthenticatedShippingRoute
  '/_authenticated/ad-accounts_/connect-meta': typeof AuthenticatedAdAccountsConnectMetaRoute
  '/_authenticated/marketers/$id': typeof AuthenticatedMarketersIdRouteWithChildren
  '/_authenticated/orders/import': typeof AuthenticatedOrdersImportRoute
  '/_authenticated/orders/update-status': typeof AuthenticatedOrdersUpdateStatusRoute
  '/_authenticated/products/$name': typeof AuthenticatedProductsNameRoute
  '/_authenticated/settings/mappings': typeof AuthenticatedSettingsMappingsRoute
  '/_authenticated/marketers/': typeof AuthenticatedMarketersIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/marketers/$id/expenses': typeof AuthenticatedMarketersIdExpensesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ad-accounts'
    | '/ad-spend'
    | '/dashboard'
    | '/orders'
    | '/products'
    | '/shipping'
    | '/ad-accounts/connect-meta'
    | '/marketers/$id'
    | '/orders/import'
    | '/orders/update-status'
    | '/products/$name'
    | '/settings/mappings'
    | '/marketers/'
    | '/orders/'
    | '/users/'
    | '/marketers/$id/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ad-accounts'
    | '/ad-spend'
    | '/dashboard'
    | '/products'
    | '/shipping'
    | '/ad-accounts/connect-meta'
    | '/marketers/$id'
    | '/orders/import'
    | '/orders/update-status'
    | '/products/$name'
    | '/settings/mappings'
    | '/marketers'
    | '/orders'
    | '/users'
    | '/marketers/$id/expenses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/ad-accounts'
    | '/_authenticated/ad-spend'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/shipping'
    | '/_authenticated/ad-accounts_/connect-meta'
    | '/_authenticated/marketers/$id'
    | '/_authenticated/orders/import'
    | '/_authenticated/orders/update-status'
    | '/_authenticated/products/$name'
    | '/_authenticated/settings/mappings'
    | '/_authenticated/marketers/'
    | '/_authenticated/orders/'
    | '/_authenticated/users/'
    | '/_authenticated/marketers/$id/expenses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shipping': {
      id: '/_authenticated/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AuthenticatedShippingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ad-spend': {
      id: '/_authenticated/ad-spend'
      path: '/ad-spend'
      fullPath: '/ad-spend'
      preLoaderRoute: typeof AuthenticatedAdSpendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ad-accounts': {
      id: '/_authenticated/ad-accounts'
      path: '/ad-accounts'
      fullPath: '/ad-accounts'
      preLoaderRoute: typeof AuthenticatedAdAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/marketers/': {
      id: '/_authenticated/marketers/'
      path: '/marketers'
      fullPath: '/marketers/'
      preLoaderRoute: typeof AuthenticatedMarketersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mappings': {
      id: '/_authenticated/settings/mappings'
      path: '/settings/mappings'
      fullPath: '/settings/mappings'
      preLoaderRoute: typeof AuthenticatedSettingsMappingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$name': {
      id: '/_authenticated/products/$name'
      path: '/$name'
      fullPath: '/products/$name'
      preLoaderRoute: typeof AuthenticatedProductsNameRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/orders/update-status': {
      id: '/_authenticated/orders/update-status'
      path: '/update-status'
      fullPath: '/orders/update-status'
      preLoaderRoute: typeof AuthenticatedOrdersUpdateStatusRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/orders/import': {
      id: '/_authenticated/orders/import'
      path: '/import'
      fullPath: '/orders/import'
      preLoaderRoute: typeof AuthenticatedOrdersImportRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/marketers/$id': {
      id: '/_authenticated/marketers/$id'
      path: '/marketers/$id'
      fullPath: '/marketers/$id'
      preLoaderRoute: typeof AuthenticatedMarketersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ad-accounts_/connect-meta': {
      id: '/_authenticated/ad-accounts_/connect-meta'
      path: '/ad-accounts/connect-meta'
      fullPath: '/ad-accounts/connect-meta'
      preLoaderRoute: typeof AuthenticatedAdAccountsConnectMetaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketers/$id/expenses': {
      id: '/_authenticated/marketers/$id/expenses'
      path: '/expenses'
      fullPath: '/marketers/$id/expenses'
      preLoaderRoute: typeof AuthenticatedMarketersIdExpensesRouteImport
      parentRoute: typeof AuthenticatedMarketersIdRoute
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersImportRoute: typeof AuthenticatedOrdersImportRoute
  AuthenticatedOrdersUpdateStatusRoute: typeof AuthenticatedOrdersUpdateStatusRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersImportRoute: AuthenticatedOrdersImportRoute,
  AuthenticatedOrdersUpdateStatusRoute: AuthenticatedOrdersUpdateStatusRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsNameRoute: typeof AuthenticatedProductsNameRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsNameRoute: AuthenticatedProductsNameRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedMarketersIdRouteChildren {
  AuthenticatedMarketersIdExpensesRoute: typeof AuthenticatedMarketersIdExpensesRoute
}

const AuthenticatedMarketersIdRouteChildren: AuthenticatedMarketersIdRouteChildren =
  {
    AuthenticatedMarketersIdExpensesRoute:
      AuthenticatedMarketersIdExpensesRoute,
  }

const AuthenticatedMarketersIdRouteWithChildren =
  AuthenticatedMarketersIdRoute._addFileChildren(
    AuthenticatedMarketersIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdAccountsRoute: typeof AuthenticatedAdAccountsRoute
  AuthenticatedAdSpendRoute: typeof AuthenticatedAdSpendRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedShippingRoute: typeof AuthenticatedShippingRoute
  AuthenticatedAdAccountsConnectMetaRoute: typeof AuthenticatedAdAccountsConnectMetaRoute
  AuthenticatedMarketersIdRoute: typeof AuthenticatedMarketersIdRouteWithChildren
  AuthenticatedSettingsMappingsRoute: typeof AuthenticatedSettingsMappingsRoute
  AuthenticatedMarketersIndexRoute: typeof AuthenticatedMarketersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdAccountsRoute: AuthenticatedAdAccountsRoute,
  AuthenticatedAdSpendRoute: AuthenticatedAdSpendRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedShippingRoute: AuthenticatedShippingRoute,
  AuthenticatedAdAccountsConnectMetaRoute:
    AuthenticatedAdAccountsConnectMetaRoute,
  AuthenticatedMarketersIdRoute: AuthenticatedMarketersIdRouteWithChildren,
  AuthenticatedSettingsMappingsRoute: AuthenticatedSettingsMappingsRoute,
  AuthenticatedMarketersIndexRoute: AuthenticatedMarketersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
